### PR TITLE
ballle98/aquaweb#8: Air and Time not showing up on home line 1

### PR DESCRIPTION
**Pull request by ballle98**
some fixes for PDA display.  Time should be on line 0 and the PDA display is only 10 lines not 12

This is what it looks like with these fixes

image

### CODE REVIEW

**Comment by ballle98** [comment]
The before images are captured here https://github.com/ballle98/aquaweb/issues/8

**Comment by earlephilhower** [comment]
Thanks again.  But let me check on this one because I don't remember seeing any sizing issue with my (very old) Jandy head unit.  I *think* there might just be different revisions of the PDA interface with different sizing so this might need to be a command line switch or something.

**Comment by ballle98** [comment]
the sizing does not cause noticeable issues you end up with 2 blank lines at the end of the screen.  writing time to line 1 instead of line 0 is more noticable.  I added a fix #8 to this pull

**Comment by ballle98** [comment]
I compared the display to the work I did on https://github.com/ballle98/AqualinkD there a debug print of home looks like there.  I normally use aqualinkd to control the pool and I linked it up to Alexa and Google home using openhab.  When lightning took out my panel and PDA I was very glad to have aquaweb to setup a replacement control board I got from ebay for $0.99.  With aquaweb and aqualinkd you can get all the features of Aqualink 2.0 on these 20 year old controllers.

```
13:04:32.450 Info:    PDA:       PDA Menu Line 0 =      THU  1:03PM
13:04:32.450 Info:    PDA:       PDA Menu Line 1 = AIR             
13:04:32.450 Info:    PDA:       PDA Menu Line 2 =  71`            
13:04:32.450 Info:    PDA:       PDA Menu Line 3 = 
13:04:32.450 Info:    PDA:       PDA Menu Line 4 = POOL MODE    OFF
13:04:32.450 Info:    PDA:       PDA Menu Line 5 = POOL HEATER  OFF
13:04:32.450 Info:    PDA:       PDA Menu Line 6 = SPA MODE     OFF
13:04:32.450 Info:    PDA:       PDA Menu Line 7 = SPA HEATER   OFF
13:04:32.450 Info:    PDA:       PDA Menu Line 8 = MENU            
13:04:32.450 Info:    PDA:       PDA Menu Line 9 = EQUIPMENT ON/OFF
13:04:32.451 Debug:   PDA:       PDA Menu highlighted line#=4 line='POOL MODE    OFF'
```

**Review by earlephilhower — APPROVED** [review]
Your comments seem spot on.  I never had an actual PDA unit so never noticed the extra lines.  Also, thx for the port update!

**Pull request merged**
